apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-appb
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-appb
  template:
    metadata:
      labels:
        app: sample-appb
    spec:
      containers:
        - name: sample-appb
          image: nginx
